### ISSUE TITLE
Default URL in on-boarding scripts is not working

### ISSUE THREAD

**Issue by gkapkowski-saucelabs** [saucelabs-training/demo-python#18]
The default on-boarding script gives an error when run with proper username and access key.

https://github.com/saucelabs-training/demo-python/blob/7997e19b5679cbb09846d0a59872d885a8300802/on-boarding-modules/python-examples/test_module1.py#L10

Only after changing the default URL to proper data center (eg. `https://ondemand.eu-central-1.saucelabs.com:443/wd/hub`) the script runs properly.

The error with default URL:
```
$ python3 onboard.py
Traceback (most recent call last):
  File "onboard.py", line 30, in <module>
    driver = webdriver.Remote(command_executor=remote_url, desired_capabilities=desired_cap)
  File "/Users/grzekorzkapkowski/Library/Python/3.8/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/Users/grzekorzkapkowski/Library/Python/3.8/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/Users/grzekorzkapkowski/Library/Python/3.8/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/grzekorzkapkowski/Library/Python/3.8/lib/python/site-packages/selenium/webdriver/remote/errorhandler.py", line 208, in check_response
    raise exception_class(value)
selenium.common.exceptions.WebDriverException: Message: Uh oh, you've run out of minutes!
Please visit https://saucelabs.com/pricing to purchase a subscription.
```

**Comment by joshmgrant** [comment]
The onboarding modules/examples are no longer present in this repo. For a comprehensive walkthrough of using Sauce Labs with Python for automated testing, see [Sauce School's Python Course](https://training.saucelabs.com/seleniumpython/). If you'd like a quick start-style example of how to use Sauce with Python, see the [best practices section](https://github.com/saucelabs-training/demo-python/tree/main/best_practice) of this repo. Thanks so much!

**Comment by shacker** [comment]
@joshmgrant I am using the best practices section of the repo and am hitting this issue. Lines in the best practices [like this](https://github.com/saucelabs-training/demo-python/blob/main/best_practice/conftest.py#L92) still reference wd/hub. I saw on StackOverflow that those URLs need to change but it's not clear to what.
